name: VPN前端

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run checkin script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: python checkin.py

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 保持仓库活跃
        uses: liskin/gh-workflow-keepalive@v1
